name: Building DTKCOMMON
run-name: ${{ github.actor }} is Building DTKCOMMON üöÄ
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building Wine
        env: 
          GUSER: ${{ secrets.GUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          UPLOADURL: ${{ secrets.UPLOADURL }}
          KEY: ${{ secrets.KEY }}
          KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
        run: |
          # ÈÖçÁΩÆÁºñËØëÂÆπÂô®
          sudo apt update
          sudo apt install lm-sensors aria2 gpg debootstrap python3 neofetch -y
          neofetch
          aria2c $KEY
          gpg --import  --pinentry-mode loopback --batch --passphrase "$KEYPASSWORD"  private-file.key
          # ÁºñËØë
          cd ~
          git clone https://$GUSER:$PASSWORD@github.com/gfdgd-xi/dde23-for-debian12-daily --depth=1
          bottle="/home/runner/dde23-for-debian12-daily/run.sh"
          chmod 777 $bottle
          $bottle apt update
          $bottle apt install sudo gpg wget git python3 dpkg-dev -y
          # Âä†Ê∫ê
          $bottle wget http://deb.debiandde.gfdgdxi.top/sources/github.sh
          $bottle bash github.sh
          $bottle rm github.sh
          sudo cp /home/runner/dde23-for-debian12-daily/build-deb.py /home/runner/debian12-chroot
          sudo cp /home/runner/dde23-for-debian12-daily/build.json /home/runner/debian12-chroot
          $bottle python3 build-deb.py
          sudo rm -rfv /home/runner/debian12-chroot/*-dbgsym_*.deb
          git config --global user.email "3025613752@qq.com"
          git config --global user.name "$GUSER"
          /home/runner/dde23-for-debian12-daily/addmore.py /home/runner/debian12-chroot/*.deb
          cd /home/runner/dde23-for-debian12-daily
          git add .
          git commit -m Ëá™Âä®Êé®ÈÄÅ
          git push
          exit
          # Êé®Ê∫ê
          git clone https://github.com/gfdgd-xi/wine-deb.git
          cd wine-deb
          git remote set-url origin https://$GUSER:$PASSWORD@github.com/gfdgd-xi/wine-deb.git
          git config --global user.email "3025613752@qq.com"
          git config --global user.name "$GUSER"
          python3 ./addmore.py --github ~/debian10-amd64/wine/*.deb ~/debian10-i386/wine/*.deb
          #git add . ; git commit -m add\ wine ; git push origin main
      